# This .gclient is generated by heahs.sh 02/16/16 16:05:35
#> chromium 47eb4b1c9f67d82534a2ec503d7927bbb02fd64d 1452757372
#> webkit e5e2f82fbba3d45573b90a71371dc2f68b9e0050 1452757682
#> skia ae36f9d5179ae4cbecc1399ab7ee0961fc1cb4da 1434420306
#> v8 1c91cb7ab92204ba1c1e0350aac0744e99321edb 1449457633
#> boringssl a07c0fc8f2181d086b1118712e2ceb0d1496fa0b 1431537582

solutions = [
{ 
  "managed": False,
  "name": "src",
  "url": "http://gerrit.mediatek.inc:8080/alps/chromium.git@47eb4b1c9f67d82534a2ec503d7927bbb02fd64d",
  "custom_deps": {
    "src": "http://gerrit.mediatek.inc:8080/alps/chromium.git@47eb4b1c9f67d82534a2ec503d7927bbb02fd64d",
    "src/third_party/WebKit": "http://gerrit.mediatek.inc:8080/alps/chromium/third_party/WebKit.git@e5e2f82fbba3d45573b90a71371dc2f68b9e0050",
    "src/third_party/skia": "http://gerrit.mediatek.inc:8080/alps/chromium/third_party/skia.git@ae36f9d5179ae4cbecc1399ab7ee0961fc1cb4da",
    "src/v8": "http://gerrit.mediatek.inc:8080/alps/chromium/v8.git@1c91cb7ab92204ba1c1e0350aac0744e99321edb",
    "src/third_party/boringssl/src": "http://gerrit.mediatek.inc:8080/alps/chromium/third_party/boringssl/src.git@a07c0fc8f2181d086b1118712e2ceb0d1496fa0b",
  },
  "deps_file": ".DEPS",
  "safesync_url": "",
},]
target_os = ['android']

